# Use an official Node.js image as a base
FROM node:14

# Set the working directory to /app
WORKDIR /client

# Copy the package*.json files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Build the frontend
RUN npm run build

# Copy the backend code
COPY ./server .

# Build the backend
#RUN npm run server

# Expose the ports
EXPOSE 80 3000

# Run the command to start the frontend
CMD ["npm", "serve"]

# Run the command to start the backend
CMD ["npm", "server"]