version: "3"

# CI/CD ONLY: Use Docker executable path for pipeline builds. Comment out or remove when running locally.
# x-docker-executable: ${DOCKER_EXECUTABLE}
x-docker-executable: /usr/bin/docker

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
